// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/daily-todo/ent/predicate"
	"github.com/dev-hyunsang/daily-todo/ent/todo"
)

// ToDoQuery is the builder for querying ToDo entities.
type ToDoQuery struct {
	config
	ctx        *QueryContext
	order      []todo.OrderOption
	inters     []Interceptor
	predicates []predicate.ToDo
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ToDoQuery builder.
func (tdq *ToDoQuery) Where(ps ...predicate.ToDo) *ToDoQuery {
	tdq.predicates = append(tdq.predicates, ps...)
	return tdq
}

// Limit the number of records to be returned by this query.
func (tdq *ToDoQuery) Limit(limit int) *ToDoQuery {
	tdq.ctx.Limit = &limit
	return tdq
}

// Offset to start from.
func (tdq *ToDoQuery) Offset(offset int) *ToDoQuery {
	tdq.ctx.Offset = &offset
	return tdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tdq *ToDoQuery) Unique(unique bool) *ToDoQuery {
	tdq.ctx.Unique = &unique
	return tdq
}

// Order specifies how the records should be ordered.
func (tdq *ToDoQuery) Order(o ...todo.OrderOption) *ToDoQuery {
	tdq.order = append(tdq.order, o...)
	return tdq
}

// First returns the first ToDo entity from the query.
// Returns a *NotFoundError when no ToDo was found.
func (tdq *ToDoQuery) First(ctx context.Context) (*ToDo, error) {
	nodes, err := tdq.Limit(1).All(setContextOp(ctx, tdq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{todo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tdq *ToDoQuery) FirstX(ctx context.Context) *ToDo {
	node, err := tdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ToDo ID from the query.
// Returns a *NotFoundError when no ToDo ID was found.
func (tdq *ToDoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tdq.Limit(1).IDs(setContextOp(ctx, tdq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{todo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tdq *ToDoQuery) FirstIDX(ctx context.Context) int {
	id, err := tdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ToDo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ToDo entity is found.
// Returns a *NotFoundError when no ToDo entities are found.
func (tdq *ToDoQuery) Only(ctx context.Context) (*ToDo, error) {
	nodes, err := tdq.Limit(2).All(setContextOp(ctx, tdq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{todo.Label}
	default:
		return nil, &NotSingularError{todo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tdq *ToDoQuery) OnlyX(ctx context.Context) *ToDo {
	node, err := tdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ToDo ID in the query.
// Returns a *NotSingularError when more than one ToDo ID is found.
// Returns a *NotFoundError when no entities are found.
func (tdq *ToDoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tdq.Limit(2).IDs(setContextOp(ctx, tdq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{todo.Label}
	default:
		err = &NotSingularError{todo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tdq *ToDoQuery) OnlyIDX(ctx context.Context) int {
	id, err := tdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ToDos.
func (tdq *ToDoQuery) All(ctx context.Context) ([]*ToDo, error) {
	ctx = setContextOp(ctx, tdq.ctx, "All")
	if err := tdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ToDo, *ToDoQuery]()
	return withInterceptors[[]*ToDo](ctx, tdq, qr, tdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tdq *ToDoQuery) AllX(ctx context.Context) []*ToDo {
	nodes, err := tdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ToDo IDs.
func (tdq *ToDoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tdq.ctx.Unique == nil && tdq.path != nil {
		tdq.Unique(true)
	}
	ctx = setContextOp(ctx, tdq.ctx, "IDs")
	if err = tdq.Select(todo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tdq *ToDoQuery) IDsX(ctx context.Context) []int {
	ids, err := tdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tdq *ToDoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tdq.ctx, "Count")
	if err := tdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tdq, querierCount[*ToDoQuery](), tdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tdq *ToDoQuery) CountX(ctx context.Context) int {
	count, err := tdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tdq *ToDoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tdq.ctx, "Exist")
	switch _, err := tdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tdq *ToDoQuery) ExistX(ctx context.Context) bool {
	exist, err := tdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ToDoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tdq *ToDoQuery) Clone() *ToDoQuery {
	if tdq == nil {
		return nil
	}
	return &ToDoQuery{
		config:     tdq.config,
		ctx:        tdq.ctx.Clone(),
		order:      append([]todo.OrderOption{}, tdq.order...),
		inters:     append([]Interceptor{}, tdq.inters...),
		predicates: append([]predicate.ToDo{}, tdq.predicates...),
		// clone intermediate query.
		sql:  tdq.sql.Clone(),
		path: tdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TodoUUID uuid.UUID `json:"todo_uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ToDo.Query().
//		GroupBy(todo.FieldTodoUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tdq *ToDoQuery) GroupBy(field string, fields ...string) *ToDoGroupBy {
	tdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ToDoGroupBy{build: tdq}
	grbuild.flds = &tdq.ctx.Fields
	grbuild.label = todo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TodoUUID uuid.UUID `json:"todo_uuid,omitempty"`
//	}
//
//	client.ToDo.Query().
//		Select(todo.FieldTodoUUID).
//		Scan(ctx, &v)
func (tdq *ToDoQuery) Select(fields ...string) *ToDoSelect {
	tdq.ctx.Fields = append(tdq.ctx.Fields, fields...)
	sbuild := &ToDoSelect{ToDoQuery: tdq}
	sbuild.label = todo.Label
	sbuild.flds, sbuild.scan = &tdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ToDoSelect configured with the given aggregations.
func (tdq *ToDoQuery) Aggregate(fns ...AggregateFunc) *ToDoSelect {
	return tdq.Select().Aggregate(fns...)
}

func (tdq *ToDoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tdq); err != nil {
				return err
			}
		}
	}
	for _, f := range tdq.ctx.Fields {
		if !todo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tdq.path != nil {
		prev, err := tdq.path(ctx)
		if err != nil {
			return err
		}
		tdq.sql = prev
	}
	return nil
}

func (tdq *ToDoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ToDo, error) {
	var (
		nodes = []*ToDo{}
		_spec = tdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ToDo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ToDo{config: tdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tdq *ToDoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tdq.querySpec()
	_spec.Node.Columns = tdq.ctx.Fields
	if len(tdq.ctx.Fields) > 0 {
		_spec.Unique = tdq.ctx.Unique != nil && *tdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tdq.driver, _spec)
}

func (tdq *ToDoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(todo.Table, todo.Columns, sqlgraph.NewFieldSpec(todo.FieldID, field.TypeInt))
	_spec.From = tdq.sql
	if unique := tdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tdq.path != nil {
		_spec.Unique = true
	}
	if fields := tdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todo.FieldID)
		for i := range fields {
			if fields[i] != todo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tdq *ToDoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tdq.driver.Dialect())
	t1 := builder.Table(todo.Table)
	columns := tdq.ctx.Fields
	if len(columns) == 0 {
		columns = todo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tdq.sql != nil {
		selector = tdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tdq.ctx.Unique != nil && *tdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tdq.predicates {
		p(selector)
	}
	for _, p := range tdq.order {
		p(selector)
	}
	if offset := tdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ToDoGroupBy is the group-by builder for ToDo entities.
type ToDoGroupBy struct {
	selector
	build *ToDoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tdgb *ToDoGroupBy) Aggregate(fns ...AggregateFunc) *ToDoGroupBy {
	tdgb.fns = append(tdgb.fns, fns...)
	return tdgb
}

// Scan applies the selector query and scans the result into the given value.
func (tdgb *ToDoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tdgb.build.ctx, "GroupBy")
	if err := tdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ToDoQuery, *ToDoGroupBy](ctx, tdgb.build, tdgb, tdgb.build.inters, v)
}

func (tdgb *ToDoGroupBy) sqlScan(ctx context.Context, root *ToDoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tdgb.fns))
	for _, fn := range tdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tdgb.flds)+len(tdgb.fns))
		for _, f := range *tdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ToDoSelect is the builder for selecting fields of ToDo entities.
type ToDoSelect struct {
	*ToDoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tds *ToDoSelect) Aggregate(fns ...AggregateFunc) *ToDoSelect {
	tds.fns = append(tds.fns, fns...)
	return tds
}

// Scan applies the selector query and scans the result into the given value.
func (tds *ToDoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tds.ctx, "Select")
	if err := tds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ToDoQuery, *ToDoSelect](ctx, tds.ToDoQuery, tds, tds.inters, v)
}

func (tds *ToDoSelect) sqlScan(ctx context.Context, root *ToDoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tds.fns))
	for _, fn := range tds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
