// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/daily-todo/ent/predicate"
	"github.com/dev-hyunsang/daily-todo/ent/todo"
)

// ToDoDelete is the builder for deleting a ToDo entity.
type ToDoDelete struct {
	config
	hooks    []Hook
	mutation *ToDoMutation
}

// Where appends a list predicates to the ToDoDelete builder.
func (tdd *ToDoDelete) Where(ps ...predicate.ToDo) *ToDoDelete {
	tdd.mutation.Where(ps...)
	return tdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tdd *ToDoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ToDoMutation](ctx, tdd.sqlExec, tdd.mutation, tdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tdd *ToDoDelete) ExecX(ctx context.Context) int {
	n, err := tdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tdd *ToDoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(todo.Table, sqlgraph.NewFieldSpec(todo.FieldID, field.TypeInt))
	if ps := tdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tdd.mutation.done = true
	return affected, err
}

// ToDoDeleteOne is the builder for deleting a single ToDo entity.
type ToDoDeleteOne struct {
	tdd *ToDoDelete
}

// Where appends a list predicates to the ToDoDelete builder.
func (tddo *ToDoDeleteOne) Where(ps ...predicate.ToDo) *ToDoDeleteOne {
	tddo.tdd.mutation.Where(ps...)
	return tddo
}

// Exec executes the deletion query.
func (tddo *ToDoDeleteOne) Exec(ctx context.Context) error {
	n, err := tddo.tdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{todo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tddo *ToDoDeleteOne) ExecX(ctx context.Context) {
	if err := tddo.Exec(ctx); err != nil {
		panic(err)
	}
}
