// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/dev-hyunsang/daily-todo/ent/runtime.go

const (
	Version = "v0.12.2"                                         // Version of ent codegen.
	Sum     = "h1:Ndl/JvCX76xCtUDlrUfMnOKBRodAtxE5yfGYxjbOxmM=" // Sum of ent codegen.
)
