// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/daily-todo/ent/todo"
	"github.com/google/uuid"
)

// ToDoCreate is the builder for creating a ToDo entity.
type ToDoCreate struct {
	config
	mutation *ToDoMutation
	hooks    []Hook
}

// SetTodoUUID sets the "todo_uuid" field.
func (tdc *ToDoCreate) SetTodoUUID(u uuid.UUID) *ToDoCreate {
	tdc.mutation.SetTodoUUID(u)
	return tdc
}

// SetNillableTodoUUID sets the "todo_uuid" field if the given value is not nil.
func (tdc *ToDoCreate) SetNillableTodoUUID(u *uuid.UUID) *ToDoCreate {
	if u != nil {
		tdc.SetTodoUUID(*u)
	}
	return tdc
}

// SetUserUUID sets the "user_uuid" field.
func (tdc *ToDoCreate) SetUserUUID(u uuid.UUID) *ToDoCreate {
	tdc.mutation.SetUserUUID(u)
	return tdc
}

// SetIsDone sets the "is_done" field.
func (tdc *ToDoCreate) SetIsDone(b bool) *ToDoCreate {
	tdc.mutation.SetIsDone(b)
	return tdc
}

// SetNillableIsDone sets the "is_done" field if the given value is not nil.
func (tdc *ToDoCreate) SetNillableIsDone(b *bool) *ToDoCreate {
	if b != nil {
		tdc.SetIsDone(*b)
	}
	return tdc
}

// SetContext sets the "context" field.
func (tdc *ToDoCreate) SetContext(s string) *ToDoCreate {
	tdc.mutation.SetContext(s)
	return tdc
}

// SetNillableContext sets the "context" field if the given value is not nil.
func (tdc *ToDoCreate) SetNillableContext(s *string) *ToDoCreate {
	if s != nil {
		tdc.SetContext(*s)
	}
	return tdc
}

// SetCreatedAt sets the "created_at" field.
func (tdc *ToDoCreate) SetCreatedAt(t time.Time) *ToDoCreate {
	tdc.mutation.SetCreatedAt(t)
	return tdc
}

// SetUpdatedAt sets the "updated_at" field.
func (tdc *ToDoCreate) SetUpdatedAt(t time.Time) *ToDoCreate {
	tdc.mutation.SetUpdatedAt(t)
	return tdc
}

// Mutation returns the ToDoMutation object of the builder.
func (tdc *ToDoCreate) Mutation() *ToDoMutation {
	return tdc.mutation
}

// Save creates the ToDo in the database.
func (tdc *ToDoCreate) Save(ctx context.Context) (*ToDo, error) {
	tdc.defaults()
	return withHooks[*ToDo, ToDoMutation](ctx, tdc.sqlSave, tdc.mutation, tdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tdc *ToDoCreate) SaveX(ctx context.Context) *ToDo {
	v, err := tdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tdc *ToDoCreate) Exec(ctx context.Context) error {
	_, err := tdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tdc *ToDoCreate) ExecX(ctx context.Context) {
	if err := tdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tdc *ToDoCreate) defaults() {
	if _, ok := tdc.mutation.TodoUUID(); !ok {
		v := todo.DefaultTodoUUID()
		tdc.mutation.SetTodoUUID(v)
	}
	if _, ok := tdc.mutation.IsDone(); !ok {
		v := todo.DefaultIsDone
		tdc.mutation.SetIsDone(v)
	}
	if _, ok := tdc.mutation.Context(); !ok {
		v := todo.DefaultContext
		tdc.mutation.SetContext(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tdc *ToDoCreate) check() error {
	if _, ok := tdc.mutation.TodoUUID(); !ok {
		return &ValidationError{Name: "todo_uuid", err: errors.New(`ent: missing required field "ToDo.todo_uuid"`)}
	}
	if _, ok := tdc.mutation.UserUUID(); !ok {
		return &ValidationError{Name: "user_uuid", err: errors.New(`ent: missing required field "ToDo.user_uuid"`)}
	}
	if _, ok := tdc.mutation.IsDone(); !ok {
		return &ValidationError{Name: "is_done", err: errors.New(`ent: missing required field "ToDo.is_done"`)}
	}
	if _, ok := tdc.mutation.Context(); !ok {
		return &ValidationError{Name: "context", err: errors.New(`ent: missing required field "ToDo.context"`)}
	}
	if _, ok := tdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ToDo.created_at"`)}
	}
	if _, ok := tdc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ToDo.updated_at"`)}
	}
	return nil
}

func (tdc *ToDoCreate) sqlSave(ctx context.Context) (*ToDo, error) {
	if err := tdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tdc.mutation.id = &_node.ID
	tdc.mutation.done = true
	return _node, nil
}

func (tdc *ToDoCreate) createSpec() (*ToDo, *sqlgraph.CreateSpec) {
	var (
		_node = &ToDo{config: tdc.config}
		_spec = sqlgraph.NewCreateSpec(todo.Table, sqlgraph.NewFieldSpec(todo.FieldID, field.TypeInt))
	)
	if value, ok := tdc.mutation.TodoUUID(); ok {
		_spec.SetField(todo.FieldTodoUUID, field.TypeUUID, value)
		_node.TodoUUID = value
	}
	if value, ok := tdc.mutation.UserUUID(); ok {
		_spec.SetField(todo.FieldUserUUID, field.TypeUUID, value)
		_node.UserUUID = value
	}
	if value, ok := tdc.mutation.IsDone(); ok {
		_spec.SetField(todo.FieldIsDone, field.TypeBool, value)
		_node.IsDone = value
	}
	if value, ok := tdc.mutation.Context(); ok {
		_spec.SetField(todo.FieldContext, field.TypeString, value)
		_node.Context = value
	}
	if value, ok := tdc.mutation.CreatedAt(); ok {
		_spec.SetField(todo.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tdc.mutation.UpdatedAt(); ok {
		_spec.SetField(todo.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ToDoCreateBulk is the builder for creating many ToDo entities in bulk.
type ToDoCreateBulk struct {
	config
	builders []*ToDoCreate
}

// Save creates the ToDo entities in the database.
func (tdcb *ToDoCreateBulk) Save(ctx context.Context) ([]*ToDo, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tdcb.builders))
	nodes := make([]*ToDo, len(tdcb.builders))
	mutators := make([]Mutator, len(tdcb.builders))
	for i := range tdcb.builders {
		func(i int, root context.Context) {
			builder := tdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ToDoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tdcb *ToDoCreateBulk) SaveX(ctx context.Context) []*ToDo {
	v, err := tdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tdcb *ToDoCreateBulk) Exec(ctx context.Context) error {
	_, err := tdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tdcb *ToDoCreateBulk) ExecX(ctx context.Context) {
	if err := tdcb.Exec(ctx); err != nil {
		panic(err)
	}
}
